### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by dieterichlawson** [slinderman/pypolyagamma#36] opened 2019-10-18 06:37 UTC
Attempting to `pip install pypolyagamma` fails with the attached error.

python version is 3.7.4
numpy version is 1.17.3
scipy version is 1.3.1

I'm on Mac os High Sierra (10.13.6)

```
pypolyagamma/pypolyagamma.cpp:16083:65: error: too many arguments to function call, expected 3, have 4
        return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                     ^~~~
    /Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/stddef.h:100:18: note: expanded from macro 'NULL'
    #    define NULL __null
                     ^~~~~~
    pypolyagamma/pypolyagamma.cpp:17439:21: error: no member named 'exc_type' in '_ts'
        *type = tstate->exc_type;
                ~~~~~~  ^
    pypolyagamma/pypolyagamma.cpp:17440:22: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?
        *value = tstate->exc_value;
                         ^~~~~~~~~
                         curexc_value
    /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    pypolyagamma/pypolyagamma.cpp:17441:19: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?
        *tb = tstate->exc_traceback;
                      ^~~~~~~~~~~~~
                      curexc_traceback
    /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    pypolyagamma/pypolyagamma.cpp:17448:24: error: no member named 'exc_type' in '_ts'
        tmp_type = tstate->exc_type;
                   ~~~~~~  ^
    pypolyagamma/pypolyagamma.cpp:17449:25: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?
        tmp_value = tstate->exc_value;
                            ^~~~~~~~~
                            curexc_value
    /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    pypolyagamma/pypolyagamma.cpp:17450:22: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?
        tmp_tb = tstate->exc_traceback;
                         ^~~~~~~~~~~~~
                         curexc_traceback
    /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    pypolyagamma/pypolyagamma.cpp:17451:13: error: no member named 'exc_type' in '_ts'
        tstate->exc_type = type;
        ~~~~~~  ^
    pypolyagamma/pypolyagamma.cpp:17452:13: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?
        tstate->exc_value = value;
                ^~~~~~~~~
                curexc_value
    /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    pypolyagamma/pypolyagamma.cpp:17453:13: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?
        tstate->exc_traceback = tb;
                ^~~~~~~~~~~~~
                curexc_traceback
    /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    pypolyagamma/pypolyagamma.cpp:17508:24: error: no member named 'exc_type' in '_ts'
        tmp_type = tstate->exc_type;
                   ~~~~~~  ^
    pypolyagamma/pypolyagamma.cpp:17509:25: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?
        tmp_value = tstate->exc_value;
                            ^~~~~~~~~
                            curexc_value
    /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    pypolyagamma/pypolyagamma.cpp:17510:22: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?
        tmp_tb = tstate->exc_traceback;
                         ^~~~~~~~~~~~~
                         curexc_traceback
    /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    pypolyagamma/pypolyagamma.cpp:17511:13: error: no member named 'exc_type' in '_ts'
        tstate->exc_type = local_type;
        ~~~~~~  ^
    pypolyagamma/pypolyagamma.cpp:17512:13: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?
        tstate->exc_value = local_value;
                ^~~~~~~~~
                curexc_value
    /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    pypolyagamma/pypolyagamma.cpp:17513:13: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?
        tstate->exc_traceback = local_tb;
                ^~~~~~~~~~~~~
                curexc_traceback
    /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    pypolyagamma/pypolyagamma.cpp:17535:24: error: no member named 'exc_type' in '_ts'
        tmp_type = tstate->exc_type;
                   ~~~~~~  ^
    pypolyagamma/pypolyagamma.cpp:17536:25: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?
        tmp_value = tstate->exc_value;
                            ^~~~~~~~~
                            curexc_value
    /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    pypolyagamma/pypolyagamma.cpp:17537:22: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?
        tmp_tb = tstate->exc_traceback;
                         ^~~~~~~~~~~~~
                         curexc_traceback
    /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    error: command 'clang' failed with exit status 1

    ----------------------------------------
Command "/Users/dlaw/dev/pg/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/9h/rr4qp1ks79j_vnq2gk9rk_0w0000gn/T/pip-install-k2tg1qp2/pypolyagamma/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/9h/rr4qp1ks79j_vnq2gk9rk_0w0000gn/T/pip-record-xnwie92l/install-record.txt --single-version-externally-managed --compile --install-headers /Users/dlaw/dev/pg/env/include/site/python3.7/pypolyagamma" failed with error code 1 in /private/var/folders/9h/rr4qp1ks79j_vnq2gk9rk_0w0000gn/T/pip-install-k2tg1qp2/pypolyagamma/
```

**Comment by dieterichlawson** [comment] 2019-10-18 06:44
Interestingly, if I install by cloning the github repository, it works.

**Comment by slinderman** [comment] 2019-10-18 15:55
Thanks for the heads up. I think this is due to a recent upgrade of cython, but I need to debug more. Jackson Loper pointed it out to me as well, and I’ve reproduced the problem on my end. Not sure how to fix it yet..

**Comment by berkgercek** [comment] 2020-02-10 15:41
Any idea on which version of cython this is failing? I'd like to use your GLM fitting tools but this is breaking the install of pyglm indirectly as a dependency.

**Comment by slinderman** [comment] 2020-06-14 00:18
I think this is fixed with the latest version on PyPI.  Try pip installing now.

**Closed by slinderman** 2020-06-14 00:18 UTC
